### ISSUE TITLE
识别本地已刮削数据功能

### ISSUE THREAD

**Issue by JerryYang-git** [msterzhang/onelist#1]
我的资源已刮削过，感觉可以添加个识别导入的选项

**Comment by msterzhang** [comment]
> 我的资源已刮削过，感觉可以添加个识别导入的选项

数据库表格式与emby或者jellyfin的格式不一样，需要单独处理下，后期考虑兼容，支持导入

**Comment by JerryYang-git** [comment]
是类似于kodi那种识别导入.nfo文件
