### ISSUE TITLE
内存占用较高

### ISSUE THREAD

**Issue by LitchiCherry** [msterzhang/onelist#15]
尤其是扫库的时候，CPU和内存占用相当高。
如果alist资源新增了，onelist是不是还要完整扫一遍？
另外期待新增telegram讨论组。

**Comment by msterzhang** [comment]
是alist占用高吧，onelist只会获取下所有文件，刮削未添加的资源

**Comment by msterzhang** [comment]
alist也是部署这台设备上吗

**Comment by msterzhang** [comment]
> > alist也是部署这台设备上吗
> 
> 是的。

我试了下，应该是一开场挂载目录，读取时候占用高，刮削过程占用就正常了

**Comment by LitchiCherry** [comment]
> > > alist也是部署这台设备上吗
> > 
> > 
> > 是的。
> 
> 我试了下，应该是一开场挂载目录，读取时候占用高，刮削过程占用就正常了

我这里还有播放连接失败，详情页图片展示不全的问题，软路由科学上网，docker桥接，应该没啥网络问题啊

**Comment by LitchiCherry** [comment]
> 播放失败自己查看alist是否打开了签名所有，需要关了

没有打开。

**Comment by LitchiCherry** [comment]
> 播放失败自己查看alist是否打开了签名所有，需要关了

有无日志文件可以查看？播放，手动削刮有点问题。

**Comment by msterzhang** [comment]
自己查看docker容器日志就行

**Comment by LitchiCherry** [comment]
> 播放失败自己查看alist是否打开了签名所有，需要关了

有无日志文件可以查看？播放，手动削刮有点问题。

**Comment by LitchiCherry** [comment]
> 播放失败自己查看alist是否打开了签名所有，需要关了

有无日志文件可以查看？播放，手动削刮有点问题。
