### ISSUE TITLE
windows端本地部署，监听端口为0（无法显示实际占用端口）

### ISSUE THREAD

**Issue by sche11** [msterzhang/onelist#19]
问题描述：
- windows端本地部署 [onelist-windows-386.zip](https://github.com/msterzhang/onelist/releases/download/v1.0.7/onelist-windows-386.zip)，打开报错`[GIN-debug] Listening and serving HTTP on :0`

- 显示监听端口为0，尝试打开 5245，5246，8080都失败。

- 可能为随机端口或端口冲突

**Comment by msterzhang** [comment]
请先用cmd初始化配置，onelist.exe -run config  在用onelist.exe -run server

**Comment by sche11** [comment]
> 请先用cmd初始化配置，onelist.exe -run config 在用onelist.exe -run server

谢谢，登陆成功
