### ISSUE TITLE
onelist播放视频相对与alist很卡

### ISSUE THREAD

**Issue by leixjtu** [msterzhang/onelist#23]
在Alist的主页里打开的阿里云盘视频可以很顺滑播放，但是在onelist之中的挂载目录中打开同一视频就会很卡，是不是意味着onelist播放的视频受到服务器带宽的限制？

**Comment by msterzhang** [comment]
onelist使用的播放链接是alist的，可能你用的是阿里云open，用的是转码后的那个视频
