### ISSUE TITLE
最新版仍然无法播放

### ISSUE THREAD

**Issue by chenryace** [msterzhang/onelist#27]
设备: N1，已安装最新版alist,版本号3.14，已禁止签名所有。onelist正常刮削成功。但仍然无法播放，用的是阿里open的链接，已确定文件格式为H264的MP4，所以真的不知道我错在哪里？ 莫非是隐私内容正则表达式那里出错？求解

**Comment by cdpeng520** [comment]
3.15.0也是一样！

**Comment by msterzhang** [comment]
刮削成功无法播放，先确认alist使用最新版，且需要alist后台关闭"签名所有功能"，还有要确认是否是浏览器不支持的编码，这种可以调用外部浏览器播放
