### ISSUE TITLE
增强刮削能力

### ISSUE THREAD

**Issue by playingapi365one** [msterzhang/onelist#29]
目前非常多电影都不能刮削出来  即使是很规范的命名  其他刮削软件可以秒刮削  onelist. 确不认，
能否兼容其他软件的命名规范

建议增加软链接功能  
把alist挂载到本地后，onelist 在其他目录建立软链接, 不对实际文件重命名  而是用新文件名建立原文件的软链接  然后 在软链接目录储存刮削信息

可以参考nastools

最好把nastools的刮削代码都移植过来

**Comment by msterzhang** [comment]
那还不如直接使用nastools得了
