### ISSUE TITLE
缓存的图片是在哪里？

### ISSUE THREAD

**Issue by icezxf** [msterzhang/onelist#45]
是在docker宿主机还是播放端

**Comment by msterzhang** [comment]
映射到宿主机器的，看docker启动时候那个目录

**Comment by icezxf** [comment]
> 映射到宿主机器的，看docker启动时候

那就是config映射的目录吗 ？另外如果是本地的alist，后面要加/dav吗 比如这样？
<img width="488" alt="image" src="https://user-images.githubusercontent.com/122969420/235389675-b8af01c1-fb7a-4cfb-9f16-9cf56cd035e8.png">
