### ISSUE TITLE
挂载目录报错

### ISSUE THREAD

**Issue by maycyc** [msterzhang/onelist#59]
群晖Docker安装
Alist访问路径有端口号
媒体中心挂载目录，按提示输入`/阿里云盘/电视剧`
`invalid character`<`looking for beginning of value
![image](https://github.com/msterzhang/onelist/assets/95576512/c34e83c3-f060-4996-997a-de202a058cd2)

**Comment by msterzhang** [comment]
alist信息哪里，地址怎么填的

**Comment by maycyc** [comment]
![image](https://github.com/msterzhang/onelist/assets/95576512/6883224e-4279-498f-bc19-13d91c81a4cb)
域名填写的是：`https://域名:5255/阿里云盘/电视剧`
端口号后面的路径没问题

**Comment by msterzhang** [comment]
这个位置只需要填前面域名：https://域名:5255，后面新建影库时候，才填路径，请认真看文档

**Comment by maycyc** [comment]
完美解决。
视频和文档都看了，太粗心。
