### ISSUE TITLE
ios17.1.2无法播放 一直转菊花

### ISSUE THREAD

**Issue by mouse0232** [msterzhang/onelist#79]
我的设备是 iphone12 ios17.1.2，使用的safari。

使用onelist 无法播放  一直转菊花。
![微信图片_20231205202814](https://github.com/msterzhang/onelist/assets/17805668/4a8e2959-52b2-4dc7-b7ee-f466ca101343)

但是使用alist的阿里云播放器可以正常播放 （如果使用video模式 也是一直转菊花）
![微信图片_20231205202822](https://github.com/msterzhang/onelist/assets/17805668/18c23333-296a-4bf5-8446-90f00279039f)

我的ipad设备 ios 16.7.2 onelist播放正常，无异常

**Comment by msterzhang** [comment]
ios系统原因，onelist层面无法解决
