### ISSUE TITLE
刮削识别率太低了

### ISSUE THREAD

**Issue by johnsyoun** [msterzhang/onelist#87]
4部纪录片，3部刮削错误，1部没刮削到；
6部国产电影，只正确识别2部，3部刮削错误，1部没刮削到；
3部国产电视剧，没有1部正确识别。
刮削错误的，都需要手工去识别、刮削。

上面这些，在Emby或者Jellyfin都是完全正确识别的。
![FireShot Capture 001 - 21 国产剧 - Alist for OpenWRT - 192 168 10 1](https://github.com/msterzhang/onelist/assets/34926325/5a625af5-a7bc-4464-8223-c0b2201afbbb)
![FireShot Capture 002 - onelist - 192 168 10 128](https://github.com/msterzhang/onelist/assets/34926325/0e4f1eb2-f5f7-4af2-b4a2-9b3a1647aef3)

**Comment by msterzhang** [comment]
注意文件名要满足文档的规则
